// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzAs1gYfdhjdsNuLYSqMYrRJfIkEByRq0',
    appId: '1:380926653855:web:cd7c484bc626a4f1f379aa',
    messagingSenderId: '380926653855',
    projectId: 'dsce-project',
    authDomain: 'dsce-project.firebaseapp.com',
    storageBucket: 'dsce-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDP4zxPYRs4afstLBdwaDWN_-3Z_dvUig',
    appId: '1:380926653855:android:98d7297b1dec0b1bf379aa',
    messagingSenderId: '380926653855',
    projectId: 'dsce-project',
    storageBucket: 'dsce-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ffhWw66D_UgGWDL0qxCmMGnxV4GJzFU',
    appId: '1:380926653855:ios:d331eaca9bb2e488f379aa',
    messagingSenderId: '380926653855',
    projectId: 'dsce-project',
    storageBucket: 'dsce-project.appspot.com',
    iosClientId: '380926653855-sjqkt6rjupnc0jcnucdhq6p6vhajo4jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ffhWw66D_UgGWDL0qxCmMGnxV4GJzFU',
    appId: '1:380926653855:ios:b833c6aadd5bbaa5f379aa',
    messagingSenderId: '380926653855',
    projectId: 'dsce-project',
    storageBucket: 'dsce-project.appspot.com',
    iosClientId: '380926653855-12j9q5vn9a702hu8aqhl4qmd81vgsknk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
